name: Application build 
run-name: building application
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔨 Start builing the docker image"
      - name: Check out repository code
        uses: actions/checkout@v4.2.0
      - run: echo "💡 The repository has been cloned to the runner."
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_PUBLISHER_LOGIN }}
          password: ${{ secrets.DOCKER_PUBLISHER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          tags: latest
          platforms: linux/amd64
          push: true
